import { model, num, pct } from "../../data/model.js";
import { Callout, NoDataYet, Note, Stat, Table } from "../ui.jsx";

export const metadata = {
  title: "Gridiron Oracle — Survivor",
  description:
    "A survivor plan computed on the model\u2019s probabilities: this week\u2019s best pick and what burning each team costs you.",
};

const BOARD_COLUMNS = [
  { key: "rank", label: "#" },
  { key: "team", label: "Team" },
  { key: "opponent", label: "Opponent", format: (v, row) => (row.home ? `vs ${v}` : `at ${v}`) },
  { key: "win_prob", label: "Win", format: (v) => pct(v) },
  { key: "survival_if_used", label: "Plan if used", format: (v) => pct(v) },
  {
    key: "advice",
    label: "Call",
    format: (v, row) => (
      <span className={`adv adv--${{ PICK: "go", SAVE: "hold", AVOID: "no" }[v] ?? "hold"}`}
            title={row.advice_why}>
        {v}
      </span>
    ),
  },
  {
    key: "cost_relative",
    // «Coste relativo» y no «coste», porque la escala es lo que lo hacía
    // ilegible: 0,0008 de probabilidad absoluta se pintaba como «−0,1%» y se
    // leía como «da igual», cuando sobre un plan que sobrevive al 0,81% son
    // **el 10% de todo lo que tienes**.
    label: "What it costs you",
    format: (v) => (v < 0.005 ? "—" : `−${pct(v, 0)}`),
  },
  {
    key: "cost",
    label: "Absolute",
    // El coste del mejor pick es cero por construcción: es el plan de
    // referencia. Escribirlo como «0,0%» invita a leerlo como un empate.
    format: (v) => (v < 1e-9 ? "—" : `−${pct(v)}`),
  },
];

/** Plan completo en una línea: la secuencia es más legible que una tabla. */
function PlanRow({ picks }) {
  return (
    <p className="plan">
      {picks.map((pick) => (
        <span className="step" key={pick.week}>
          <span className="wk">J{pick.week}</span>
          <span className="tm">{pick.team}</span>
          <span className="pb">{pct(pick.win_prob, 0)}</span>
        </span>
      ))}
    </p>
  );
}

export default function Survivor() {
  const survivor = model.survivor;

  if (!survivor) {
    return (
      <>
        <h1>Survivor</h1>
        <p className="lede">
          One winner a week, no team twice. Miss one and you are out.
        </p>
        <NoDataYet />
        <p className="caption">
          This section is generated by <code>python scripts/survivor_build.py</code>.
        </p>
      </>
    );
  }

  const best = survivor.short_board?.[0];
  const weeks = survivor.through - survivor.from_week + 1;

  return (
    <>
      <h1>
        Survivor — week {survivor.from_week}, {survivor.season}
      </h1>
      <p className="lede">
        One winner a week, no team twice. The hard call is not who wins Sunday: it is what it
        costs you to spend today the team that would have saved week eleven.
      </p>

      <Note title="Here the model does add something, for a specific reason">
        <p>
          Against the closing line the model ties, which is why the betting page comes up
          empty. In a survivor pool <strong>you are not competing against an efficient
          market</strong>: you are competing against the schedule and against your own pool of
          teams. What is needed is not a better probability than the market&rsquo;s but a{" "}
          <strong>well-calibrated</strong> one — measured, ECE{" "}
          {num(model.validation?.overall?.ece ?? 0, 4)} — plus looking at every week at once,
          which is where a person runs out of room.
        </p>
      </Note>

      <div className="grid">
        <Stat
          label="Best pick"
          value={best ? best.team : "—"}
          hint={best ? `${best.home ? "vs" : "at"} ${best.opponent} · wins ${pct(best.win_prob)}` : null}
        />
        <Stat
          label={`Survive ${survivor.short_horizon} weeks`}
          value={pct(survivor.short_survival)}
          hint="With the optimal plan"
        />
        <Stat
          label={`Survive all ${weeks}`}
          value={pct(survivor.plan_survival, 2)}
          hint="The number nobody shows"
        />
        <Stat
          label="Teams used"
          value={survivor.used.length}
          hint={survivor.used.length ? survivor.used.join(", ") : "None yet"}
        />
      </div>

      <Callout title="Surviving the whole season is nearly impossible, and worth knowing">
        <p>
          The <em>optimal</em> plan — the best path that exists given these probabilities —
          reaches the end <strong>{pct(survivor.plan_survival, 2)}</strong> of the time. That is
          not a model failure: it is the arithmetic of multiplying {weeks} probabilities of
          about 70%. A survivor pool is not won by surviving, it is won by lasting longer than
          everyone else.
        </p>
      </Callout>

      <h2>Week {survivor.from_week}, looking {survivor.short_horizon} weeks ahead</h2>
      <p className="caption">
        Sorted by the survival of the best plan that <em>starts</em> with that team, not by
        who wins most clearly on Sunday. The last column is the difference: what you lose by
        spending them today instead of at their best moment.
      </p>
      <Table columns={BOARD_COLUMNS} rows={survivor.short_board ?? []} />
      <p className="caption">
        The short plan that comes out of this:
      </p>
      <PlanRow picks={survivor.short_plan ?? []} />

      <h2>The same calculation across the full season</h2>
      <p className="caption">
        Over {weeks} weeks the product of probabilities flattens and the options stop being
        distinguishable: everything comes out &ldquo;under one percent&rdquo;. Useful for seeing
        the path, not for deciding Sunday.
      </p>
      <Table columns={BOARD_COLUMNS} rows={survivor.board ?? []} />
      <PlanRow picks={survivor.plan ?? []} />

      <h2>What this calculation does not do</h2>
      <ul>
        <li>
          <strong>It does not model the rest of the pool.</strong> In a large pool it is
          sometimes worth diverging from the public favorite even at a cost in probability:
          sharing elimination with everyone does not eliminate you, and sharing survival with
          everyone does not win it. That needs to know what people are picking, and we do not
          have it.
        </li>
        <li>
          <strong>Distant weeks are not forecasts.</strong> No market line is published for a
          future week, so the model falls back to its standalone variant, which is worse (Brier
          0.2187 against 0.2117 in the backtest). Week 15 computed today is a team-strength
          prior.
        </li>
        <li>
          <strong>It knows nothing about injuries.</strong> Like the rest of the project. The{" "}
          <a href="/research">injury report</a> sits beside it, never inside it.
        </li>
        <li>
          <strong>The final week is its own case.</strong> Teams already locked into the
          playoffs rest starters, and the model does not know it.
        </li>
      </ul>

      <h2>How it is calculated</h2>
      <p>
        Maximizing the probability of surviving every week means maximizing the product of the
        win probabilities, which means maximizing the <strong>sum of their logarithms</strong>
        subject to one team per week and no repeats. That is a linear assignment problem: it has
        an exact solution via the Hungarian algorithm and runs in milliseconds. Nothing needs to
        be simulated.
      </p>
      <p className="caption">
        The cost of burning a team comes from solving it twice: the free optimum, and the
        optimum forced to use that team this week. The difference <em>is</em> the cost.
      </p>
    </>
  );
}
